default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: microlearn_quiz_development
  username: postgres
  password: 123123

test:
  <<: *default
  database: microlearn_quiz_test
  username: postgres
  password: 123123

production:
  <<: *default
  database: microlearn_quiz_production
  username: microlearn_quiz
  password: <%= ENV["MICROLEARN_QUIZ_DATABASE_PASSWORD"] %>
